build:
  version: "1.0"

cards:
  message: "Welcome to BloodBank accounts related to prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@bloodbank.com"
  onCallSupport:
    -(453)435-4353
    -(345)344-6436